/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbeans_modules_cnd_clang_jni_CXTranslationUnit */

#ifndef _Included_org_netbeans_modules_cnd_clang_jni_CXTranslationUnit
#define _Included_org_netbeans_modules_cnd_clang_jni_CXTranslationUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXTranslationUnit
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXTranslationUnit_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXTranslationUnit
 * Method:    allocate
 * Signature: (J[BJI[[B)J
 */
JNIEXPORT jlong JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXTranslationUnit_allocate
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
