/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList */

#ifndef _Included_org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList
#define _Included_org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList
 * Method:    allocate
 * Signature: ([[B[[B)J
 */
JNIEXPORT jlong JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList_allocate
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList
 * Method:    getCXUnsavedFilePointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXUnsavedFileList_getCXUnsavedFilePointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
