/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbeans_modules_cnd_clang_jni_CXIndex */

#ifndef _Included_org_netbeans_modules_cnd_clang_jni_CXIndex
#define _Included_org_netbeans_modules_cnd_clang_jni_CXIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXIndex
 * Method:    allocate
 * Signature: (ZZI)J
 */
JNIEXPORT jlong JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXIndex_allocate
  (JNIEnv *, jclass, jboolean, jboolean, jint);

/*
 * Class:     org_netbeans_modules_cnd_clang_jni_CXIndex
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_netbeans_modules_cnd_clang_jni_CXIndex_deallocate
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
