////
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
////

= Post-donation changes

The following changes have been made in this module in order to compile after
the donation, and some pending enhancements and things to do.

== LongHashMap.java

// Copied from org.netbeans.modules.parsing.impl.indexing, should this be in util?;
The file "LongHashMap.java" was not donated by Oracle in the 4th donation, and is was copied into src\org\netbeans\modules\cnd\repository\util from the parsing.indexing module.

== UTF

The file "UTF.8" was not donated by Oracle in the 4th donation, a quick replacement was done to get the module compiling, but further analysis is required to see if we are introducing a performance bottleneck.




