/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.cnd.lsp.client.impl.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.eclipse.lsp4j.MessageActionItem;

/**
 *
 * @author antonio
 */
public class ShowMessageRequestPanel extends javax.swing.JPanel {

    private DefaultComboBoxModel<String> comboBoxModel;
    private final List<MessageActionItem> actionItems;

    /**
     * Creates new form ShowMessageRequestPanel
     */
    public ShowMessageRequestPanel(String message, List<MessageActionItem> actionItems) {
        this.actionItems = actionItems;
        initComponents();
        lblMessage.setText("<html>" + message + "</html>");
        comboBoxModel = new DefaultComboBoxModel<>();
        actionItems.stream().forEach(actionItem -> comboBoxModel.addElement(actionItem.getTitle()));
        optActions.setModel(comboBoxModel);
    }

    public MessageActionItem getSelectedMessageActionItem() {
        int index = optActions.getSelectedIndex();
        return 0 <= index && index < actionItems.size() ? actionItems.get(index) : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblMessage = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        optActions = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(lblMessage, org.openide.util.NbBundle.getMessage(ShowMessageRequestPanel.class, "ShowMessageRequestPanel.lblMessage.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(lblMessage, gridBagConstraints);

        lblNote.setFont(lblNote.getFont().deriveFont(lblNote.getFont().getSize()-3f));
        org.openide.awt.Mnemonics.setLocalizedText(lblNote, org.openide.util.NbBundle.getMessage(ShowMessageRequestPanel.class, "ShowMessageRequestPanel.lblNote.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(lblNote, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        add(optActions, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNote;
    private javax.swing.JComboBox<String> optActions;
    // End of variables declaration//GEN-END:variables
}
